@extends('layout')
@section('title','Menu | Dine In')
@section('content')
<div class="hero"><p>WELCOME TO OUR TABLE</p><h1>Good food, served with warmth.</h1><p>Browse our menu and place your order right here.</p></div>
@if(!$orderDetails)
<div class="panel"><h2>Start your order</h2><form method="post" action="{{ route('start') }}">@csrf <div class="grid customer-details-grid"><div><label for="name">Customer name</label><input id="name" name="name" type="text" maxlength="100" required value="{{ old('name') }}" placeholder="Enter customer name"></div><div><label for="phone">Mobile number <span class="muted">(optional)</span></label><input id="phone" name="phone" type="text" inputmode="tel" maxlength="10" value="{{ old('phone') }}" placeholder="Enter mobile number"></div><div><label for="payment_method">Pay via</label><select id="payment_method" name="payment_method" required><option value="cash">Cash</option><option value="upi">UPI</option><option value="card">Card</option></select></div></div><p><button type="submit">Start order</button></p></form></div>
@else
<div class="panel"><strong>Ordering for {{ $orderDetails['name'] }}</strong> <span class="muted">&middot; Choose foods and quantities below.</span></div>
@if($orderDetails['payment_method'] === 'upi')
<div class="panel" style="text-align:center"><h2>UPI payment</h2>@if($paymentQrCode)<p>Place your order to see the final amount and open GPay, PhonePe, or another UPI app. You can also scan this QR code.</p><img src="{{ asset('storage/'.$paymentQrCode->image_path) }}" alt="Restaurant UPI QR code" style="width:min(100%,220px);height:auto;background:white;padding:8px"><p class="muted">Your payment will remain unpaid until staff confirms it.</p>@else<p>UPI QR is not set up yet. Ask staff for payment details after ordering.</p>@endif</div>
@endif
<nav class="chips">@foreach($categories as $category)<a href="#category-{{ $category->id }}">{{ $category->name }}</a>@endforeach</nav>
<form method="post" action="{{ route('orders.store') }}" id="order-form">@csrf <input type="hidden" name="name" value="{{ $orderDetails['name'] }}"><input type="hidden" name="phone" value="{{ $orderDetails['phone'] }}"><input type="hidden" name="payment_method" value="{{ $orderDetails['payment_method'] }}">@foreach($categories as $category)<section id="category-{{ $category->id }}"><h2>{{ $category->name }}</h2>@if($category->description)<p class="muted">{{ $category->description }}</p>@endif<div class="grid">@forelse($category->products as $product)<article class="card"><div class="photo">@if($product->image_path)<img src="{{ asset('storage/'.$product->image_path) }}" alt="{{ $product->name }}">@else <span>Plate</span>@endif</div><div class="card-body"><h3>{{ $product->name }}</h3><p class="muted">{{ $product->description }}</p><div class="row" style="justify-content:space-between"><span class="price">Rs. {{ number_format($product->price,2) }}</span><div><label for="qty-{{ $product->id }}">Qty</label><input class="qty" id="qty-{{ $product->id }}" type="number" min="0" max="50" value="0" data-id="{{ $product->id }}" data-name="{{ $product->name }}" data-price="{{ $product->price }}"></div></div></div></article>@empty <p class="muted">Items coming soon.</p>@endforelse</div></section>@endforeach<div class="order-bar panel"><strong>Selected items</strong><div id="selected-items" class="selected-items"><span class="muted">No food selected.</span></div><div class="charges"><div class="selected-item"><span>Other charges</span><strong>Rs. 0.00</strong></div><div class="selected-item"><strong>Total</strong><strong>Rs. <span id="total">0.00</span></strong></div></div><button type="submit">Place order</button></div></form>
<script>const form=document.querySelector('#order-form'),quantities=[...document.querySelectorAll('.qty')],itemsBox=document.querySelector('#selected-items');function refresh(){let sum=0;const selected=[];quantities.forEach(q=>{const quantity=Number(q.value)||0,price=Number(q.dataset.price);if(quantity){const line=quantity*price;sum+=line;selected.push(`<div class="selected-item"><span>${q.dataset.name} x ${quantity}</span><strong>Rs. ${line.toFixed(2)}</strong></div>`)}});itemsBox.innerHTML=selected.join('')||'<span class="muted">No food selected.</span>';document.querySelector('#total').textContent=sum.toFixed(2)}quantities.forEach(q=>q.addEventListener('input',refresh));form.addEventListener('submit',e=>{form.querySelectorAll('.generated').forEach(x=>x.remove());let selected=quantities.filter(q=>Number(q.value)>0);if(!selected.length){e.preventDefault();alert('Choose at least one food item.');return}selected.forEach((q,i)=>{for(const [key,value] of [['id',q.dataset.id],['quantity',q.value]]){let input=document.createElement('input');input.type='hidden';input.className='generated';input.name=`items[${i}][${key}]`;input.value=value;form.append(input)}})})</script>
@endif
@endsection
