@extends('layout')
@section('title','Generate order')
@section('content')
<div class="row" style="justify-content:space-between"><div><p class="muted" style="margin:0">ADMIN ORDER</p><h1>Generate order</h1></div><a class="btn" href="{{ route('admin.dashboard') }}">Dashboard</a></div>
<form method="post" action="{{ route('admin.orders.store') }}" id="admin-order-form">@csrf
<section class="panel"><div class="grid customer-details-grid"><div><label for="customer-name">Customer name</label><input id="customer-name" name="name" list="customer-names" required autocomplete="off" placeholder="Type a customer name"><datalist id="customer-names">@foreach($customerNames as $name)<option value="{{ $name }}">@endforeach</datalist></div><div><label for="customer-mobile">Mobile number <span class="muted">(optional)</span></label><input id="customer-mobile" name="phone" type="text" inputmode="tel" maxlength="10"></div><div><label for="admin-payment-status">Payment status</label><select id="admin-payment-status" name="payment_status"><option value="unpaid">Unpaid</option><option value="paid">Paid</option><option value="credit">Credit (Udhari)</option></select></div><div><label for="admin-payment-method">Received via</label><select id="admin-payment-method" name="payment_method"><option value="cash">Cash</option><option value="upi">UPI</option><option value="card">Card</option></select></div></div></section>
<section class="panel"><div class="food-search-box"><label for="food-search">Search food</label><input id="food-search" type="search" placeholder="Type a food name"></div><nav class="chips">@foreach($categories as $category)<a href="#admin-category-{{ $category->id }}">{{ $category->name }}</a>@endforeach</nav>@foreach($categories as $category)<section id="admin-category-{{ $category->id }}"><h2>{{ $category->name }}</h2><div class="grid">@foreach($category->products as $product)<article class="card admin-food" data-food="{{ strtolower($product->name.' '.$product->description) }}"><div class="photo">@if($product->image_path)<img src="{{ asset('storage/'.$product->image_path) }}" alt="{{ $product->name }}">@else <span>Plate</span>@endif</div><div class="card-body"><h3>{{ $product->name }}</h3><p class="muted">{{ $product->description }}</p><div class="row" style="justify-content:space-between"><span class="price">Rs. {{ number_format($product->price,2) }}</span><div><label for="admin-qty-{{ $product->id }}">Qty</label><input class="qty" id="admin-qty-{{ $product->id }}" type="number" min="0" max="50" value="0" data-id="{{ $product->id }}" data-name="{{ $product->name }}" data-price="{{ $product->price }}"></div></div></div></article>@endforeach</div></section>@endforeach</section>
<div class="order-bar panel"><strong>Selected items</strong><div id="admin-selected-items" class="selected-items"><span class="muted">No food selected.</span></div><div class="charges"><div class="selected-item"><span>Other charges</span><strong>Rs. 0.00</strong></div><div class="selected-item"><strong>Total</strong><strong>Rs. <span id="admin-total">0.00</span></strong></div></div><button type="submit">Create order and print</button></div></form>
<script>const adminForm=document.querySelector('#admin-order-form'),adminQuantities=[...document.querySelectorAll('.qty')],foodSearch=document.querySelector('#food-search'),adminItemsBox=document.querySelector('#admin-selected-items');function adminRefresh(){let total=0;const selected=[];adminQuantities.forEach(input=>{const quantity=Number(input.value)||0,price=Number(input.dataset.price);if(quantity){const line=quantity*price;total+=line;selected.push(`<div class="selected-item"><span>${input.dataset.name} x ${quantity}</span><strong>Rs. ${line.toFixed(2)}</strong></div>`)}});adminItemsBox.innerHTML=selected.join('')||'<span class="muted">No food selected.</span>';document.querySelector('#admin-total').textContent=total.toFixed(2)}adminQuantities.forEach(input=>input.addEventListener('input',adminRefresh));foodSearch.addEventListener('input',()=>{const query=foodSearch.value.trim().toLowerCase();document.querySelectorAll('.admin-food').forEach(card=>card.hidden=query&&!card.dataset.food.includes(query))});adminForm.addEventListener('submit',event=>{adminForm.querySelectorAll('.generated').forEach(input=>input.remove());const selected=adminQuantities.filter(input=>Number(input.value)>0);if(!selected.length){event.preventDefault();alert('Choose at least one food item.');return}selected.forEach((input,index)=>[['id',input.dataset.id],['quantity',input.value]].forEach(([key,value])=>{const field=document.createElement('input');field.type='hidden';field.name=`items[${index}][${key}]`;field.value=value;field.className='generated';adminForm.append(field)}))})</script>
@endsection
