@extends('layout')
@section('title',__('Generate order'))
@section('content')
@include('admin.nav')
<div class="row" style="justify-content:space-between"><div><p class="muted">{{ __('ADMIN ORDER') }}</p><h1>{{ __('Generate order') }}</h1></div></div>
<form method="post" action="{{ route('admin.orders.store') }}" id="admin-order-form">@csrf
<section class="panel"><div class="grid customer-details-grid">
    <div><label for="customer-name">{{ __('Customer name') }}</label><input id="customer-name" name="name" list="customer-names" required autocomplete="off" placeholder="{{ __('Type a customer name') }}"><datalist id="customer-names">@foreach($customerNames as $name)<option value="{{ $name }}">@endforeach</datalist></div>
    <div><label for="customer-mobile">{{ __('Mobile number') }} ({{ __('optional') }})</label><input id="customer-mobile" name="phone" type="tel" inputmode="numeric" maxlength="10"></div>
    <div><label for="admin-payment-status">{{ __('Payment status') }}</label><select id="admin-payment-status" name="payment_status"><option value="unpaid">{{ __('Unpaid') }}</option><option value="paid">{{ __('Paid') }}</option><option value="credit">{{ __('Credit (Udhari)') }}</option></select></div>
    <div><label for="admin-payment-method">{{ __('Received via') }}</label><select id="admin-payment-method" name="payment_method"><option value="cash">{{ __('Cash') }}</option><option value="upi">UPI</option><option value="card">{{ __('Card') }}</option></select></div>
</div></section>
<section class="panel"><div class="food-search-box"><label for="food-search">{{ __('Search food') }}</label><input id="food-search" type="search" placeholder="{{ __('Type a food name') }}"></div>
    <nav class="chips">@foreach($categories as $category)<a href="#admin-category-{{ $category->id }}">{{ $category->display_name }}</a>@endforeach</nav>
    @foreach($categories as $category)<section id="admin-category-{{ $category->id }}"><h2>{{ $category->display_name }}</h2><div class="product-row">
        @foreach($category->products as $product)<article class="card admin-food" data-food="{{ strtolower($product->name.' '.$product->name_mr.' '.$product->description.' '.$product->description_mr) }}"><div class="photo">@if($product->image_path)<img src="{{ asset('storage/'.$product->image_path) }}" alt="{{ $product->display_name }}">@else <span>{{ __('Plate') }}</span>@endif</div><div class="card-body"><h3>{{ $product->display_name }}</h3><p class="muted">{{ $product->display_description }}</p><div class="row" style="justify-content:space-between"><span class="price">₹{{ number_format($product->price,2) }}</span><div><label for="admin-qty-{{ $product->id }}">{{ __('Qty') }}</label><input class="qty" id="admin-qty-{{ $product->id }}" type="number" min="0" max="50" value="0" data-id="{{ $product->id }}" data-name="{{ $product->display_name }}" data-price="{{ $product->price }}"></div></div></div></article>@endforeach
    </div></section>@endforeach
</section>
<div class="order-bar panel"><strong>{{ __('Selected items') }}</strong><div id="admin-selected-items" class="selected-items"><span class="muted">{{ __('No food selected.') }}</span></div><div class="charges"><div class="selected-item"><span>{{ __('Other charges') }}</span><strong>₹0.00</strong></div><div class="selected-item"><strong>{{ __('Total') }}</strong><strong>₹<span id="admin-total">0.00</span></strong></div></div><button type="submit">{{ __('Create order and print') }}</button></div>
</form>
<script>
const adminForm=document.querySelector('#admin-order-form'),adminQuantities=[...document.querySelectorAll('.qty')],foodSearch=document.querySelector('#food-search'),adminItemsBox=document.querySelector('#admin-selected-items');
function adminRefresh(){let total=0,count=0;adminItemsBox.replaceChildren();adminQuantities.forEach(input=>{const quantity=Number(input.value)||0,price=Number(input.dataset.price);if(quantity>0){count++;const line=quantity*price;total+=line;const row=document.createElement('div'),name=document.createElement('span'),amount=document.createElement('strong');row.className='selected-item';name.textContent=`${input.dataset.name} × ${quantity}`;amount.textContent=`₹${line.toFixed(2)}`;row.append(name,amount);adminItemsBox.append(row)}});if(!count){const empty=document.createElement('span');empty.className='muted';empty.textContent=@json(__('No food selected.'));adminItemsBox.append(empty)}document.querySelector('#admin-total').textContent=total.toFixed(2)}
adminQuantities.forEach(input=>input.addEventListener('input',adminRefresh));foodSearch.addEventListener('input',()=>{const query=foodSearch.value.trim().toLowerCase();document.querySelectorAll('.admin-food').forEach(card=>card.hidden=!!query&&!card.dataset.food.includes(query))});adminForm.addEventListener('submit',event=>{adminForm.querySelectorAll('.generated').forEach(input=>input.remove());const selected=adminQuantities.filter(input=>Number(input.value)>0);if(!selected.length){event.preventDefault();alert(@json(__('Choose at least one food item.')));return}selected.forEach((input,index)=>[['id',input.dataset.id],['quantity',input.value]].forEach(([key,value])=>{const field=document.createElement('input');field.type='hidden';field.name=`items[${index}][${key}]`;field.value=value;field.className='generated';adminForm.append(field)}))})
</script>
@endsection
